### ISSUE TITLE
Issue with logging path

### ISSUE THREAD

**Issue by dorianweidler** [andifalk/secure-oauth2-oidc-workshop#14]
`Failed to read or configure the org.jboss.logmanager.LogManager
java.lang.IllegalArgumentException: Failed to instantiate class "org.jboss.logmanager.handlers.PeriodicRotatingFileHandler" for handler "FILE"
	at org.jboss.logmanager@2.1.11.Final//org.jboss.logmanager.config.AbstractPropertyConfiguration$ConstructAction.validate(AbstractPropertyConfiguration.java:117)
	at org.jboss.logmanager@2.1.11.Final//org.jboss.logmanager.config.LogContextConfigurationImpl.doPrepare(LogContextConfigurationImpl.java:336)
	at org.jboss.logmanager@2.1.11.Final//org.jboss.logmanager.config.LogContextConfigurationImpl.prepare(LogContextConfigurationImpl.java:289)
	at org.jboss.logmanager@2.1.11.Final//org.jboss.logmanager.config.LogContextConfigurationImpl.commit(LogContextConfigurationImpl.java:298)
	at org.jboss.logmanager@2.1.11.Final//org.jboss.logmanager.PropertyConfigurator.configure(PropertyConfigurator.java:546)
	at org.jboss.logmanager@2.1.11.Final//org.jboss.logmanager.PropertyConfigurator.configure(PropertyConfigurator.java:97)
	at org.jboss.logmanager@2.1.11.Final//org.jboss.logmanager.LogManager.readConfiguration(LogManager.java:170)
	at org.jboss.logmanager@2.1.11.Final//org.jboss.logmanager.LogManager.readConfiguration(LogManager.java:132)
	at java.logging/java.util.logging.LogManager.readPrimordialConfiguration(LogManager.java:445)
	at java.logging/java.util.logging.LogManager$2.run(LogManager.java:394)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:312)
	at java.logging/java.util.logging.LogManager.ensureLogManagerInitialized(LogManager.java:382)
	at java.logging/java.util.logging.LogManager.getLogManager(LogManager.java:430)
	at org.jboss.modules.Main.main(Main.java:523)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
	at org.jboss.logmanager@2.1.11.Final//org.jboss.logmanager.config.AbstractPropertyConfiguration$ConstructAction.validate(AbstractPropertyConfiguration.java:115)
	... 13 more
Caused by: java.io.FileNotFoundException: /home/afa/Documents/spring_io/keycloak-7.0.0/standalone/log/server.log (No such file or directory)
	at java.base/java.io.FileOutputStream.open0(Native Method)
	at java.base/java.io.FileOutputStream.open(FileOutputStream.java:292)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:235)
	at org.jboss.logmanager@2.1.11.Final//org.jboss.logmanager.handlers.FileHandler.setFile(FileHandler.java:151)
	at org.jboss.logmanager@2.1.11.Final//org.jboss.logmanager.handlers.PeriodicRotatingFileHandler.setFile(PeriodicRotatingFileHandler.java:104)
	at org.jboss.logmanager@2.1.11.Final//org.jboss.logmanager.handlers.FileHandler.setFileName(FileHandler.java:189)
	at org.jboss.logmanager@2.1.11.Final//org.jboss.logmanager.handlers.FileHandler.<init>(FileHandler.java:119)
	at org.jboss.logmanager@2.1.11.Final//org.jboss.logmanager.handlers.PeriodicRotatingFileHandler.<init>(PeriodicRotatingFileHandler.java:72)
	... 19 more`

Will be fixed with Issue #9

**Comment by andifalk** [comment]
@dorianweidler I think you meant it will be fixed with #11

**Comment by dorianweidler** [comment]
Fixed #9 and hotfixed #14 with the same new prepared keycloak installation.
Long-term solution for #14 will be in #11.
